// ============================================================
// CATÁLOGOS COMPARTIDOS — Fundación Exalumnos UCR
// ============================================================

export const CARRERAS_UCR = [
  'Administración de Negocios',
  'Agronomía',
  'Arquitectura',
  'Artes',
  'Biología',
  'Ciencias de la Computación e Informática',
  'Ciencias Políticas',
  'Comunicación Colectiva',
  'Contaduría Pública',
  'Derecho',
  'Diseño Gráfico',
  'Economía',
  'Educación',
  'Enfermería',
  'Farmacia',
  'Filosofía',
  'Física',
  'Geografía',
  'Historia',
  'Ingeniería Civil',
  'Ingeniería Eléctrica',
  'Ingeniería Industrial',
  'Ingeniería Mecánica',
  'Ingeniería Química',
  'Letras',
  'Matemáticas',
  'Medicina',
  'Microbiología',
  'Música',
  'Nutrición',
  'Odontología',
  'Psicología',
  'Química',
  'Salud Pública',
  'Sociología',
  'Trabajo Social',
  'Zootecnia',
]

export const ESCUELAS_UCR = [
  'Escuela de Administración de Negocios',
  'Escuela de Agronomía',
  'Escuela de Arquitectura',
  'Escuela de Artes Plásticas',
  'Escuela de Biología',
  'Escuela de Ciencias de la Computación e Informática (ECCI)',
  'Escuela de Ciencias Políticas',
  'Escuela de Ciencias del Movimiento Humano',
  'Escuela de Comunicación Colectiva',
  'Escuela de Contaduría Pública',
  'Escuela de Derecho',
  'Escuela de Diseño Gráfico',
  'Escuela de Economía',
  'Escuela de Educación',
  'Escuela de Enfermería',
  'Escuela de Estudios Generales',
  'Escuela de Farmacia',
  'Escuela de Filosofía',
  'Escuela de Física',
  'Escuela de Geografía',
  'Escuela de Historia',
  'Escuela de Ingeniería Civil',
  'Escuela de Ingeniería Eléctrica',
  'Escuela de Ingeniería Industrial',
  'Escuela de Ingeniería Mecánica',
  'Escuela de Ingeniería Química',
  'Escuela de Letras',
  'Escuela de Matemáticas',
  'Escuela de Medicina',
  'Escuela de Microbiología',
  'Escuela de Música',
  'Escuela de Nutrición',
  'Escuela de Odontología',
  'Escuela de Psicología',
  'Escuela de Química',
  'Escuela de Salud Pública',
  'Escuela de Sociología',
  'Escuela de Trabajo Social',
  'Escuela de Zootecnia',
  'Facultad de Ciencias',
  'Facultad de Ciencias Agroalimentarias',
  'Facultad de Ciencias Económicas',
  'Facultad de Ciencias Sociales',
  'Facultad de Derecho',
  'Facultad de Educación',
  'Facultad de Ingeniería',
  'Facultad de Letras',
  'Facultad de Medicina',
  'Facultad de Microbiología',
  'Facultad de Odontología',
]

export const SECTORES_INDUSTRIA = [
  'Tecnología e Informática',
  'Finanzas y Banca',
  'Salud y Ciencias Médicas',
  'Educación e Investigación',
  'Derecho y Consultoría Legal',
  'Ingeniería y Construcción',
  'Agroindustria y Alimentación',
  'Marketing y Comunicaciones',
  'Emprendimiento y Startups',
  'Organismos Internacionales y ONG',
  'Gobierno y Sector Público',
  'Arte, Cultura y Entretenimiento',
  'Comercio y Retail',
  'Recursos Humanos',
  'Logística y Cadena de Suministro',
  'Turismo y Hotelería',
  'Bienes Raíces',
  'Energía y Medio Ambiente',
  'Farmacéutica y Biotecnología',
  'Manufactura e Industria',
]

export const AREAS_INTERES = [
  'Tecnología e Innovación',
  'Salud y Bienestar',
  'Educación y Formación',
  'Emprendimiento',
  'Ambiente y Sostenibilidad',
  'Arte y Cultura',
  'Derechos Humanos',
  'Finanzas y Economía',
  'Agroindustria',
  'Políticas Públicas',
  'Investigación Científica',
  'Comunicación y Medios',
  'Bienestar Social',
  'Ingeniería y Manufactura',
]

export const TIPOS_APOYO = [
  { key: 'ofrece_mentoria', label: 'Mentoría', icon: '🎓' },
  { key: 'ofrece_empleo', label: 'Empleo', icon: '💼' },
  { key: 'ofrece_pasantia', label: 'Pasantía', icon: '📋' },
  { key: 'ofrece_proyecto', label: 'Colaboración en Proyecto', icon: '🤝' },
  { key: 'ofrece_donacion_dinero', label: 'Donación Económica', icon: '💰' },
] as const
