import { EstudianteDirectorio } from "../types/estudiantes";

export const MOCK_ESTUDIANTES: EstudianteDirectorio[] = [
  {
    user_id: "user-1",
    nombre: "María Fernanda Quesada",
    foto_url: null, // Probar fallback
    carrera: "Ingeniería Química",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Desarrollo de Bioplásticos a base de Cáscara de Piña",
    proyecto_area_tematica: "Desarrollo Sostenible",
    proyecto_tipo: "Trabajo Final de Graduación",
    proyecto_porcentaje_avance: 85,
    areas_de_interes: ["Biotecnología", "Economía Circular"],
    busca_financiamiento: true,
    busca_mentoria: true,
    busca_empleo: false,
    busca_pasantia: false,
    escuela_facultad: "Facultad de Ingeniería",
    proyecto_descripcion: "Este proyecto tiene como objetivo desarrollar bioplásticos sostenibles a partir de la cáscara de piña, un desecho agrícola abundante en Costa Rica. El material resultante es biodegradable en menos de 90 días bajo condiciones de compostaje y tiene una resistencia mecánica comparable a los plásticos convencionales de un solo uso.",
  },
  {
    user_id: "user-2",
    nombre: "Alejandro Brenes",
    foto_url: null,
    carrera: "Computación",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "IA para Detección de Plagas en Cacao",
    proyecto_area_tematica: "Ciencia y Tecnología",
    proyecto_tipo: "Práctica Dirigida",
    proyecto_porcentaje_avance: 40,
    areas_de_interes: ["Machine Learning", "Agritech"],
    busca_financiamiento: false,
    busca_mentoria: true,
    busca_empleo: true,
    busca_pasantia: false,
  },
  {
    user_id: "user-3",
    nombre: "Sofía Valverde",
    foto_url: null,
    carrera: "Psicología",
    sede: "Sede de Occidente",
    proyecto_titulo: "Impacto del Trabajo Remoto en la Salud Mental",
    proyecto_area_tematica: "Ciencias Sociales",
    proyecto_tipo: "Tesis",
    proyecto_porcentaje_avance: 65,
    areas_de_interes: ["Recursos Humanos", "Psicología Organizacional"],
    busca_financiamiento: false,
    busca_mentoria: true,
    busca_empleo: false,
    busca_pasantia: true,
  },
  {
    user_id: "user-4",
    nombre: "Diego Mora",
    foto_url: null,
    carrera: "Ingeniería Eléctrica",
    sede: "Sede del Pacífico",
    proyecto_titulo: "Prototipo de Boya Inteligente para Monitoreo Oceánico",
    proyecto_area_tematica: "Ciencia y Tecnología",
    proyecto_tipo: "Trabajo Final de Graduación",
    proyecto_porcentaje_avance: 15,
    areas_de_interes: ["IoT", "Energías Renovables"],
    busca_financiamiento: true,
    busca_mentoria: true,
    busca_empleo: false,
    busca_pasantia: false,
  },
  {
    user_id: "user-5",
    nombre: "Laura Rojas",
    foto_url: null,
    carrera: "Nutrición",
    sede: "Sede del Atlántico",
    proyecto_titulo: "Guía Nutricional para Pacientes Diabéticos en Zonas Rurales",
    proyecto_area_tematica: "Ciencias de la Salud",
    proyecto_tipo: "Proyecto de Investigación",
    proyecto_porcentaje_avance: 95,
    areas_de_interes: ["Salud Pública", "Educación"],
    busca_financiamiento: false,
    busca_mentoria: false,
    busca_empleo: true,
    busca_pasantia: false,
  },
  {
    user_id: "user-6",
    nombre: "Carlos Jiménez",
    foto_url: null,
    carrera: "Ingeniería Industrial",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Optimización de Procesos Logísticos",
    proyecto_area_tematica: "Ciencia y Tecnología",
    proyecto_tipo: "Trabajo Final de Graduación",
    proyecto_porcentaje_avance: 55,
    areas_de_interes: ["Logística", "Gestión de Calidad"],
    busca_financiamiento: false,
    busca_mentoria: true,
    busca_empleo: true,
    busca_pasantia: false,
  },
  {
    user_id: "user-7",
    nombre: "Andrea Salazar",
    foto_url: null,
    carrera: "Sociología",
    sede: "Sede de Occidente",
    proyecto_titulo: "Dinámicas Sociales en Comunidades Rurales",
    proyecto_area_tematica: "Ciencias Sociales",
    proyecto_tipo: "Proyecto de Investigación",
    proyecto_porcentaje_avance: 75,
    areas_de_interes: ["Investigación Cualitativa", "Desarrollo Rural"],
    busca_financiamiento: true,
    busca_mentoria: false,
    busca_empleo: false,
    busca_pasantia: false,
  },
  {
    user_id: "user-8",
    nombre: "Pablo Castro",
    foto_url: null,
    carrera: "Diseño Gráfico",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Campaña Visual para Concientización Ambiental",
    proyecto_area_tematica: "Artes y Letras",
    proyecto_tipo: "Práctica Dirigida",
    proyecto_porcentaje_avance: 90,
    areas_de_interes: ["UX/UI", "Branding"],
    busca_financiamiento: false,
    busca_mentoria: true,
    busca_empleo: true,
    busca_pasantia: true,
  },
  {
    user_id: "user-9",
    nombre: "Valeria Guzmán",
    foto_url: null,
    carrera: "Biología",
    sede: "Sede del Pacífico",
    proyecto_titulo: "Conservación de Especies Marinas Endémicas",
    proyecto_area_tematica: "Desarrollo Sostenible",
    proyecto_tipo: "Tesis",
    proyecto_porcentaje_avance: 25,
    areas_de_interes: ["Biología Marina", "Ecología"],
    busca_financiamiento: true,
    busca_mentoria: true,
    busca_empleo: false,
    busca_pasantia: false,
  },
  {
    user_id: "user-10",
    nombre: "Luis Monge",
    foto_url: null,
    carrera: "Ingeniería Mecánica",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Diseño de Prótesis de Bajo Costo",
    proyecto_area_tematica: "Ciencia y Tecnología",
    proyecto_tipo: "Trabajo Final de Graduación",
    proyecto_porcentaje_avance: 80,
    areas_de_interes: ["Biomecánica", "Impresión 3D"],
    busca_financiamiento: true,
    busca_mentoria: true,
    busca_empleo: false,
    busca_pasantia: false,
  },
  {
    user_id: "user-11",
    nombre: "Mariana Lobo",
    foto_url: null,
    carrera: "Odontología",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Impacto de Hábitos Alimenticios en Salud Bucal Infantil",
    proyecto_area_tematica: "Ciencias de la Salud",
    proyecto_tipo: "Proyecto de Investigación",
    proyecto_porcentaje_avance: 45,
    areas_de_interes: ["Salud Pública", "Odontopediatría"],
    busca_financiamiento: false,
    busca_mentoria: false,
    busca_empleo: false,
    busca_pasantia: true,
  },
  {
    user_id: "user-12",
    nombre: "Daniela Vargas",
    foto_url: null,
    carrera: "Matemática",
    sede: "Sede Rodrigo Facio",
    proyecto_titulo: "Modelado Matemático de Tráfico Urbano",
    proyecto_area_tematica: "Ciencia y Tecnología",
    proyecto_tipo: "Tesis",
    proyecto_porcentaje_avance: 60,
    areas_de_interes: ["Data Science", "Estadística"],
    busca_financiamiento: false,
    busca_mentoria: true,
    busca_empleo: true,
    busca_pasantia: false,
  }
];
