-- MIGRACIÓN 02: Crear tabla carreras y relaciones muchos a muchos

CREATE TABLE IF NOT EXISTS public.carreras (
  id_carreras int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  nombre varchar,
  descripcion text
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.carreras ENABLE ROW LEVEL SECURITY;

-- Política para permitir que cualquier usuario autenticado o anónimo lea las carreras
CREATE POLICY "carreras_select_all"
  ON public.carreras FOR SELECT
  USING (true);

-- ============================================================
-- RELACIONES MUCHOS A MUCHOS (Carreras <-> Exalumnos/Estudiantes)
-- ============================================================

-- Tabla intermedia para exalumnos y carreras
CREATE TABLE IF NOT EXISTS public.exalumnos_carreras (
  exalumno_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  carrera_id int8 REFERENCES public.carreras(id_carreras) ON DELETE CASCADE,
  PRIMARY KEY (exalumno_id, carrera_id)
);

ALTER TABLE public.exalumnos_carreras ENABLE ROW LEVEL SECURITY;
CREATE POLICY "exalumnos_carreras_select_all" ON public.exalumnos_carreras FOR SELECT USING (true);
CREATE POLICY "exalumnos_carreras_insert_own" ON public.exalumnos_carreras FOR INSERT WITH CHECK (auth.uid() = exalumno_id);

-- Tabla intermedia para estudiantes y carreras
CREATE TABLE IF NOT EXISTS public.estudiantes_carreras (
  estudiante_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  carrera_id int8 REFERENCES public.carreras(id_carreras) ON DELETE CASCADE,
  PRIMARY KEY (estudiante_id, carrera_id)
);

ALTER TABLE public.estudiantes_carreras ENABLE ROW LEVEL SECURITY;
CREATE POLICY "estudiantes_carreras_select_all" ON public.estudiantes_carreras FOR SELECT USING (true);
CREATE POLICY "estudiantes_carreras_insert_own" ON public.estudiantes_carreras FOR INSERT WITH CHECK (auth.uid() = estudiante_id);

-- Eliminar las columnas estáticas de las tablas originales, 
-- ya que ahora se usará la relación.
ALTER TABLE public.exalumnos DROP COLUMN IF EXISTS carrera_ucr;
ALTER TABLE public.estudiantes DROP COLUMN IF EXISTS carrera;
