-- MIGRACIÓN 03: Crear tabla facultades y limpiar tablas de usuarios

CREATE TABLE IF NOT EXISTS public.facultades (
  id_facultades int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  nombre varchar,
  descripcion text
);

ALTER TABLE public.facultades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "facultades_select_all" ON public.facultades FOR SELECT USING (true);

-- Agregar llave foránea a la tabla carreras existente
ALTER TABLE public.carreras ADD COLUMN IF NOT EXISTS id_facultades int8 REFERENCES public.facultades(id_facultades) ON DELETE SET NULL;

-- Eliminar de forma permanente la columna redundante de la tabla usuarios,
-- ya que la facultad se conocerá a través de la relación:
-- usuario -> exalumnos_carreras -> carreras -> facultades
ALTER TABLE public.exalumnos DROP COLUMN IF EXISTS escuela_facultad;
ALTER TABLE public.estudiantes DROP COLUMN IF EXISTS escuela_facultad;
