-- ==============================================================================
-- MIGRACIÓN 12: Refactor de Esquema y Migración de Datos Segura
-- Este script aplica los cambios estructurales optimizados conservando datos.
-- ==============================================================================

BEGIN;

-- ==============================================================================
-- 1. CREACIÓN DE CATÁLOGOS V2
-- ==============================================================================
CREATE TABLE public.facultades_v2 (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_id bigint UNIQUE,
    nombre varchar(150) NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

-- Migrar campus
CREATE TABLE public.campus_v2 (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_id uuid UNIQUE,
    nombre varchar(150) NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

INSERT INTO public.campus_v2 (old_id, nombre, created_at)
SELECT id, short_name, created_at FROM public.ucr_campuses ON CONFLICT (nombre) DO NOTHING;

-- Migrar carreras
CREATE TABLE public.carreras_v2 (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_id bigint UNIQUE,
    facultad_id smallint REFERENCES public.facultades_v2(id) ON DELETE RESTRICT,
    nombre varchar(200) NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.carreras_v2 ALTER COLUMN facultad_id DROP NOT NULL;

INSERT INTO public.carreras_v2 (old_id, nombre, created_at)
SELECT id_carreras, nombre, created_at FROM public.carreras ON CONFLICT (nombre) DO NOTHING;

-- Migrar carrera_campus
CREATE TABLE public.carrera_campus_v2 (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_id uuid UNIQUE,
    carrera_id integer NOT NULL REFERENCES public.carreras_v2(id) ON DELETE CASCADE,
    campus_id smallint NOT NULL REFERENCES public.campus_v2(id) ON DELETE CASCADE,
    UNIQUE(carrera_id, campus_id)
);

INSERT INTO public.carrera_campus_v2 (old_id, carrera_id, campus_id)
SELECT cc.id, c2.id, camp2.id
FROM public.carrera_campus cc
JOIN public.carreras_v2 c2 ON cc.id_carrera = c2.old_id
JOIN public.campus_v2 camp2 ON cc.campus_id = camp2.old_id
ON CONFLICT (carrera_id, campus_id) DO NOTHING;

-- ==============================================================================
-- 2. MODIFICAR PUBLIC.USERS Y MIGRAR PERFILES
-- ==============================================================================
ALTER TABLE public.users 
  ADD COLUMN IF NOT EXISTS rol varchar(20) CHECK (rol IN ('estudiante', 'exalumno', 'admin')),
  ADD COLUMN IF NOT EXISTS apellidos varchar(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS busca_mentoria boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS busca_empleo boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ofrece_mentoria boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS visible_en_directorio boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS carrera_principal_id integer REFERENCES public.carrera_campus_v2(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone NULL;

-- Asimilar tipo a rol y remover nulos para aplicar constraint
UPDATE public.users SET rol = tipo WHERE rol IS NULL;
ALTER TABLE public.users ALTER COLUMN rol SET NOT NULL;

-- Migrar metadatos de exalumnos a users
UPDATE public.users u
SET 
  ofrece_mentoria = e.ofrece_mentoria,
  visible_en_directorio = e.visible_en_directorio
FROM public.exalumnos e
WHERE u.id = e.user_id;

-- Migrar metadatos de estudiantes a users
UPDATE public.users u
SET 
  busca_mentoria = es.busca_mentoria,
  busca_empleo = es.busca_empleo,
  visible_en_directorio = es.visible_en_directorio,
  carrera_principal_id = (SELECT id FROM public.carrera_campus_v2 WHERE old_id = es.id_carrera_campus LIMIT 1)
FROM public.estudiantes es
WHERE u.id = es.user_id;

-- ==============================================================================
-- 3. MIGRACIÓN HACIA CURRICULUMS
-- ==============================================================================
-- Renombramos fk y agregamos campos nuevos
ALTER TABLE public.curriculum RENAME COLUMN estudiante_id TO user_id;

ALTER TABLE public.curriculum
  ADD COLUMN IF NOT EXISTS sobre_mi text,
  ADD COLUMN IF NOT EXISTS url_linkedin varchar(255),
  ADD COLUMN IF NOT EXISTS url_portfolio varchar(255);

-- Migrar bio de exalumnos (usamos DO UPDATE por si ya tenían curriculum creado)
INSERT INTO public.curriculum (user_id, sobre_mi, url_linkedin)
SELECT user_id, bio, linkedin_url FROM public.exalumnos
ON CONFLICT (user_id) DO UPDATE 
SET sobre_mi = EXCLUDED.sobre_mi, url_linkedin = EXCLUDED.url_linkedin;

-- Restablecer constraints
ALTER TABLE public.curriculum DROP CONSTRAINT IF EXISTS curriculum_estudiante_id_key CASCADE;
ALTER TABLE public.curriculum DROP CONSTRAINT IF EXISTS curriculum_estudiante_id_fkey CASCADE;
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_user_id_key UNIQUE (user_id);

-- Estandarizar nombre plural
ALTER TABLE public.curriculum RENAME TO curriculums;

-- ==============================================================================
-- 4. NUEVAS TABLAS DE RELACIÓN (Users_Carreras y Experiencia)
-- ==============================================================================
CREATE TABLE public.users_carreras (
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    carrera_campus_id integer NOT NULL REFERENCES public.carrera_campus_v2(id) ON DELETE CASCADE,
    anio_ingreso smallint,
    anio_graduacion smallint,
    PRIMARY KEY (user_id, carrera_campus_id)
);

-- Migrar historial carreras de exalumnos
INSERT INTO public.users_carreras (user_id, carrera_campus_id, anio_graduacion)
SELECT ec.exalumno_id, ccv2.id, ec.anio_graduacion
FROM public.exalumno_carreras ec
JOIN public.carrera_campus_v2 ccv2 ON ec.id_carrera_campus = ccv2.old_id
ON CONFLICT (user_id, carrera_campus_id) DO NOTHING;

-- Crear tabla Experiencia Laboral universal y migrar datos
CREATE TABLE public.experiencia_laboral (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    empresa varchar(150) NOT NULL,
    puesto varchar(150) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    descripcion text,
    actualmente_aqui boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

INSERT INTO public.experiencia_laboral (id, user_id, empresa, puesto, fecha_inicio, fecha_fin, descripcion)
SELECT ce.id, c.user_id, ce.organizacion, ce.titulo, ce.fecha_inicio, ce.fecha_fin, array_to_string(ce.bullets, ' - ')
FROM public.curriculum_experiencia ce
JOIN public.curriculums c ON ce.curriculum_id = c.id;

-- ==============================================================================
-- 5. LIMPIEZA DE TABLAS OBSOLETAS
-- ==============================================================================
DROP TABLE IF EXISTS public.exalumno_carreras CASCADE;
DROP TABLE IF EXISTS public.curriculum_experiencia CASCADE;
DROP TABLE IF EXISTS public.estudiantes CASCADE;
DROP TABLE IF EXISTS public.exalumnos CASCADE;
DROP TABLE IF EXISTS public.carrera_campus CASCADE;
DROP TABLE IF EXISTS public.carreras CASCADE;
DROP TABLE IF EXISTS public.ucr_campuses CASCADE;
DROP TABLE IF EXISTS public.ucr_faculties CASCADE;
DROP TABLE IF EXISTS public.facultades CASCADE;
DROP TABLE IF EXISTS public.campus CASCADE;

-- Renombrar V2 a tablas finales
ALTER TABLE public.facultades_v2 RENAME TO facultades;
ALTER TABLE public.campus_v2 RENAME TO campus;
ALTER TABLE public.carreras_v2 RENAME TO carreras;
ALTER TABLE public.carrera_campus_v2 RENAME TO carrera_campus;

-- Eliminar columnas temporales de migración
ALTER TABLE public.facultades DROP COLUMN IF EXISTS old_id;
ALTER TABLE public.campus DROP COLUMN IF EXISTS old_id;
ALTER TABLE public.carreras DROP COLUMN IF EXISTS old_id;
ALTER TABLE public.carrera_campus DROP COLUMN IF EXISTS old_id;
ALTER TABLE public.users DROP COLUMN IF EXISTS tipo CASCADE;

-- ==============================================================================
-- 6. TRIGGERS Y FUNCIONES
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.on_auth_user_created()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, rol, nombre, apellidos)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'rol', 'estudiante'),
        COALESCE(NEW.raw_user_meta_data->>'nombre', 'Usuario'),
        COALESCE(NEW.raw_user_meta_data->>'apellidos', '')
    );
    RETURN NEW;
EXCEPTION
    WHEN others THEN
        RAISE WARNING 'Error sincronizando usuario %: %', NEW.id, SQLERRM;
        RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recrear Auth Trigger
DROP TRIGGER IF EXISTS on_auth_user_created_trigger ON auth.users;
CREATE TRIGGER on_auth_user_created_trigger
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.on_auth_user_created();

-- Update Trigger
DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ==============================================================================
-- 7. REFORZAR RLS E ÍNDICES
-- ==============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curriculums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiencia_laboral ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean AS $$
BEGIN
  RETURN (current_setting('request.jwt.claims', true)::jsonb ->> 'user_role') = 'admin';
END;
$$ LANGUAGE plpgsql STABLE;

-- Actualizar políticas básicas
DROP POLICY IF EXISTS "users_select_authenticated" ON public.users;
CREATE POLICY "Directorio publico" ON public.users FOR SELECT 
USING (visible_en_directorio = true AND deleted_at IS NULL);

DROP POLICY IF EXISTS "users_update_own" ON public.users;
CREATE POLICY "Modificar propio perfil" ON public.users FOR UPDATE 
USING (auth.uid() = id) 
WITH CHECK (auth.uid() = id);

-- Índices Parciales B-Tree
CREATE INDEX IF NOT EXISTS idx_users_busca_mentoria ON public.users (id) WHERE busca_mentoria = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_busca_empleo ON public.users (id) WHERE busca_empleo = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_directorio ON public.users (id) WHERE visible_en_directorio = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_carrera_principal ON public.users (carrera_principal_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_email ON public.users (email) WHERE deleted_at IS NULL;

-- Índices GIN
CREATE INDEX IF NOT EXISTS idx_curriculums_hab_blandas ON public.curriculums USING GIN (habilidades_blandas);
CREATE INDEX IF NOT EXISTS idx_curriculums_hab_tecnicas ON public.curriculums USING GIN (habilidades_tecnicas);

COMMIT;
